### ISSUE TITLE
Separating functionality of File and Directory

### ISSUE THREAD

**Issue by gweiying** [isomerpages/isomercms-backend#113]
As discussed in the context of #108, currently the distinction between files and folders is not conceptually clear on our backend. We currently use the File class to retrieve and list files in Collection, Resource etc, but we should move that functionality to the separate Directory class, and use File class for editing and handling only single files. 

We can afford to leave this refactoring for later since it does not affect the current page/folder re-ordering work.

**Comment by kwajiehao** [comment]
Refactoring has been done in #108

**Comment by prestonlimlianjie** [comment]
We are currently tackling this in the CMS refactor
