### ISSUE TITLE
Extend `File` class for collection pages

### ISSUE THREAD

**Issue by kwajiehao** [isomerpages/isomercms-backend#125]
## Overview

With the shift to Jekyll v4, each collection/folder has a collection/folder config file which keeps track of the order of pages within a folder. Therefore, when moving a page to and from different folders, we will also need to update the the config files of all folders involved. This is currently done by separately instantiating the `CollectionConfig` class and using the methods to add and remove items from the folder config file.

This is conceptually clunky, since the actions related to the `CollectionConfig` must necessarily occur when we're moving pages to and from folders. Therefore, we propose to extend the `File` class to create a folder/collection page class whose `create` and `delete` methods are overridden so that the updates to `CollectionConfig` are done as part of those methods.

**Comment by prestonlimlianjie** [comment]
Stale
