### ISSUE TITLE
Set up version and release tooling

### ISSUE THREAD

**Issue by prestonlimlianjie** [isomerpages/isomercms-backend#157]
Use the [`auto-changelog` library](https://www.npmjs.com/package/auto-changelog) to generate release documentation.

Follow the [Releases 101 document](https://docs.google.com/document/d/1XqRxgKBzRPkH0iS3Gy4RAq5E4T1z-Fz1qXpsn2zWIGQ/edit#) to perform releases for isomerCMS

**Comment by seaerchin** [comment]
closed by #340
