### ISSUE TITLE
Renaming subfolders in view of future template change 

### ISSUE THREAD

**Issue by kwajiehao** [isomerpages/isomercms-backend#202]
## Description
Currently, when we rename subfolders/third nav folders, we fail to also rename the `third_nav_title` attribute within that subfolder's pages. PR #200 fixes this bug by individually modifying each of the files in the subfolder. This isn't great, since the amount of time taken to rename the folder scales proportionally with the number of files in that folder. Furthermore, this change affects all folders, even though the original bug only affects subfolder pages. Unfortunately, this is the only solution since we need to modify each individual file's front matter.

However, we eventually plan on modifying our templates so that we no longer rely on the `third_nav_title` attribute when building Isomer sites. When that is done, we can return to our current way of renaming folders using Git trees, which is a lot more performant.

## To-do
- Revert PR #200 when we fix our templates to not rely on `third_nav_title` but on the `collections.yml` file instead

**Comment by prestonlimlianjie** [comment]
Stale
