### ISSUE TITLE
Improve file hierarchy endpoint to use Git Data API

### ISSUE THREAD

**Issue by taufiq** [isomerpages/isomercms-backend#22]
Calling the endpoint to list the file hierarchy makes multiple API calls currently. Is there a more efficient way?

**Comment by taufiqmmhd** [comment]
Update: I do not know what endpoint this issue is referring to and I probably should've been more specific.

**Comment by kwajiehao** [comment]
Closed because original author was not specific enough for us to know what this issue was about
