### ISSUE TITLE
[Refactor] Convert backend classes to use dependency injection

### ISSUE THREAD

**Issue by alexanderleegs** [isomerpages/isomercms-backend#232]
Our current classes are difficult to test, due to the large chain of dependencies which make classes difficult to test. As part of the refactor, we intend to convert our new classes to use dependency injections, allowing for more independent behaviour which can be stubbed in tests easily.

**Comment by seaerchin** [comment]
@alexanderleegs do we still have any left? if i remember correctly, it should be all done right

**Comment by alexanderleegs** [comment]
Yep this should be done - closing the issue
