### ISSUE TITLE
[Identity] Whitelisting of domains

### ISSUE THREAD

**Issue by alexanderleegs** [isomerpages/isomercms-backend#381]
Our current proposed method for whitelisting domains is to store them in an env var - this may be infeasible in the long term because [AWS restricts the length of env vars](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-cfg-softwaresettings.html#environments-cfg-softwaresettings-console):
```
- Keys can contain up to 128 characters. Values can contain up to 256 characters.

- The combined size of all environment properties cannot exceed 4,096 bytes when stored as strings with the format key=value.
```

As the number of whitelisted domains is expected to grow, we should look into storing them in a table and referencing from it instead of using env vars.

**Comment by jacksonOGP** [comment]
to add on context. New email domains can come up on either any of these scenarios

- agency creating a division (mha.gov.sg created new domain for hta.gov.sg awhile back)
- agency creating several new teams/departments
- organisation creating temporary emails for vendor, even tho it's .gov.sg, there's additional field in the domain, root domain doesn't really change

**Comment by jacksonOGP** [comment]
Update after speaking with Hong, we might have to whitelist even more Vendors for future upcoming migration. Do take note of this flow since I believe we will hit character limits pretty soon
