### ISSUE TITLE
To whitelist all healthcare domains by 12 May

### ISSUE THREAD

**Issue by kathleenkhy** [isomerpages/isomercms-backend#428]
To whitelist healthcare domains in the table [here](https://docs.google.com/document/d/1Pdiia7BWV82VMbqWfZmBQic95ZOYB6wBxYSlQoKchbc/edit#heading=h.jor1u18v1v28) by 12 May after moving to RDS so that healthcare users will be able to access Isomer's CMS when OGP announces products for use to Healthcare institutions in May

Given a healthcare user with email domain from [here](https://docs.google.com/document/d/1Pdiia7BWV82VMbqWfZmBQic95ZOYB6wBxYSlQoKchbc/edit#heading=h.jor1u18v1v28) has GitHub access to Isomer's CMS
When they access the Isomer CMS page and verify their email domain in the pop up modal
They will be able to access the CMS and use Isomer

**Comment by seaerchin** [comment]
@alexanderleegs wdyt about doing this tomorrow with the shift to using the db tables?

**Comment by alexanderleegs** [comment]
Resolved with #433!
