### ISSUE TITLE
[BUG] Additional parameter being passed to FE

### ISSUE THREAD

**Issue by seaerchin** [isomerpages/isomercms-backend#454]
**Description**
see [here](https://github.com/isomerpages/isomercms-frontend/pull/931#discussion_r897647436) for a description. basically, our BE is passing an extra param called `resources_name` back to frontend, which will cause the type-checking to fail on the frontend and leads to extra work to omit this param. 

**Suggested Solution**
delete the parameter

**Comment by alexanderleegs** [comment]
We should also be passing the param `url` to the frontend - this is the param that a repo's `robots.txt` draws from, which is currently unavailable for users to modify via the cms, and not having it properly set up affects the SEO of a site. We should also modify the params passed to include this value + add the additional field to the settings page on the frontend.
