### ISSUE TITLE
[TESTS] Notification tests destructively interfere with other integration tests

### ISSUE THREAD

**Issue by seaerchin** [isomerpages/isomercms-backend#564]
**Describe the bug**
At present, the tests in `integration/notifications.spec` have been skipped. If they are not skipped, the tests will cause the integration tests involving the `User` table to fail due to query creation.

**To Reproduce**
1. delete the `.skip` in `integration/notification.spec`'s first `describe` block
2. run `npm run test`

**Comment by alexanderleegs** [comment]
Resolved by #572 - issue was caused due to concurrency in tests
